apiVersion: v1
kind: Pod
metadata:
  name: {{ include "shawshank-api-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "shawshank-api-chart.name" . }}
    helm.sh/chart: {{ include "shawshank-api-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: curl
      image: radial/busyboxplus:curl
      command: ['curl']
      args:  ['{{ include "shawshank-api-chart.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}']
  restartPolicy: Never
