type: object
description: 商品实例表
example:
  id: 1
  uuid: '218b269a-784e-4fdd-8621-e4e2fb64e469'
  product_id: 1
  package_id: 1
  created_at: '2018-06-06T06:06:06Z'
  updated_at: '2018-06-06T06:06:06Z'
properties:
  id:
    type: integer
    description: 包装盒ID
  uuid:
    type: string
    description: 商品唯一编码
  product_id:
    type: integer
    description: 商品id
  product:
    $ref: '#/components/schemas/Product'
    description: 对应的商品
  package_id:
    type: integer
    description: 包装盒id
  package:
    $ref: '#/components/schemas/Package'
    description: 对应的包装
  created_at:
    type: date-time
    description: 创建时间
  updated_at:
    type: date-time
    description: 更新时间
